name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: course.prafdin.ru
          port: 3154
          username: romaerror5
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # остановиться при любой ошибке

            echo '${{ secrets.GHCR_TOKEN }}' | docker login ghcr.io -u romaerror5 --password-stdin

            cd /home/romaerror5/Desktop/devops/catty-reminders-app

            git fetch origin
            git checkout lab4
            git reset --hard origin/lab4

            ls -la docker-compose.yaml

            docker compose down --volumes || true

            docker compose up -d --remove-orphans

            docker compose ps